[package]
name = "priority_queue"
version = "0.1.0"
edition = "2024"

[dependencies]
critical-section = "1.2.0"

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }

[features]
std = ["critical-section/std"]
